### ISSUE TITLE
Error: TypeError: NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by ghost** [confused-Techie/Tabby#2]
## Info about browser
Browser: Firefox
Tabby version: Tabby 1.0 for Firefox

## Context
I see that for some reason, there is an error which outputs:

```
Error: TypeError: NetworkError when attempting to fetch resource.
```

![image](https://user-images.githubusercontent.com/108250871/192128004-9ec48d29-1e07-4b95-9a59-f95d288cec99.png)

**Comment by confused-Techie** [comment]
Thanks for reporting this issue @softcode589.

To make sure we can properly diagnose it do you mind if we sort out a few questions.

* Are you able to reach you hosted Tabby instance without issue?
* Is the Website you are attempting to save filtered/blocked/or otherwise generally inaccessible as far as you know?
* Have you double checked you extension settings to ensure its pointing to the right Tabby Instance?

**Comment by ghost** [comment]
> * Is the Website you are attempting to save filitered/blocked/or otherwise generally inaccessible as far as you know?

It appeared when I clicked "Add Bookmark".

> * Are you able to reach you hosted Tabby instance without issue?

What do you even mean by the "hosted Tabby instance"?

> * Have you double checked you extension settings to ensure its pointing to the right Tabby Instance?

I have only one Tabby instance, and settings unchanged.

**Comment by confused-Techie** [comment]
Ah I see. So what you have installed in Firefox is the [Tabby Firefox Extension](https://github.com/confused-Techie/TabbyFirefoxExtension)

The extension itself attempts to communicate with a hosted instance of the [Tabby Server](https://github.com/confused-Techie/Tabby).

While making this more clear when installing the extension can absolutely be done, what this means is that with no Tabby Server to contact, the extension will error out when attempting to save a bookmark. Which also can probably be made more clear.

I'd recommend following the [Installation Documentation](https://github.com/confused-Techie/Tabby#installation) to get the Tabby Server setup, and then it can communicate with the extension.
